### PR TITLE
Do not call "Clang" while editing in comments

### PR DESCRIPTION
**Pull request by YorkZ**

### CODE REVIEW

**Comment by brianjcj** [comment]
what is the problem exactly? clang itself can tell whether it is in comment/string or not, and will not complete things when it is.
Is this your case: you set ac-auto-start to t, and don't like clang being invoked even though it will not complete anything?

**Comment by YorkZ** [comment]
My `ac-auto-start' setting is 2. The problem I was having was that for each character I typed in the comment area, clang always reported the error "clang failed with error 1: ...", I didn't attach the rest of the error message, but that was a lot, and because of this the speed suffered a lot while typing comments. I was using clang 2.9 but now I'm using v3.2, still getting the same results. Can you test on your system and take a look into the "_Messages_" buffer?

**Comment by brianjcj** [comment]
Ok. I have changed the codes. Please take a look.

**Comment by YorkZ** [comment]
Your fix differs from mine and it works as well. However, I think using `syntax-ppss' is slower than checking for`font-lock-comment-face' directly because the face has been set by cc-mode already (cc-mode has done the hard work to calculate the proper face), while calling `syntax-ppss' will cause a lot of time consuming parsing which is unnecessary as cc-mode has already done the hard work. Since this code is being called every time a character has been pressed, the speed is pretty important.

**Comment by brianjcj** [comment]
The font-lock framework actually replies on the syntax framework to parse comment/string, and the cc-mode only need to tell the syntax framework how the comment/string will be started and ended. The syntax parsing is actually performed automatically when we are typing. And it is smart enough not to do everything from scratch, instead, it will base on the previous parsing result. So in most cases, it only needs to do a little work.
And the font-lock is optional function and can be turned off. So I don't want to depend on it.
Generally, I like to use syntax-ppss since it is more accurate. The font-lock can be delayed and font-lock will be not triggered if the text is not on the screen.

**Pull request closed without merging**
